<?php
/**
 * Implements hook_theme().
 */
function regiotoken_wallet_theme($existing, $type, $theme, $path) {
  return [
    'regiotoken_wallet' => [
      'variables' => [
        'balance' => 0.00,
        'symbol' => 'REGIO',
        'address' => '',
        'transactions' => [],
      ],
      'template' => 'regiotoken-wallet',
      'path' => $path . '/templates',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for regiotoken_wallet template.
 */
function regiotoken_wallet_preprocess_regiotoken_wallet(&$variables) {
  // CSRF Token für das Formular generieren
  $variables['form_token'] = \Drupal::csrfToken()->get('wallet_transfer_form');
  
  // Token an drupalSettings übergeben
  $variables['#attached']['drupalSettings']['token'] = $variables['form_token'];
}
